apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: prod-slack-client
  labels:
    app: slack-client
    env: prod
spec:
  replicas: 1
  selector:
    app: slack-client
    env: prod
  triggers:
    - type: ImageChange
      imageChangeParams:
        containerNames:
          - slack-client
        from:
          kind: ImageStreamTag
          name: slack-client:latest
  template:
    metadata:
      labels:
        app: slack-client
        env: prod
    spec:
      containers:
        - name: slack-client
          image: kscout/slack-client:latest
          env:
            - name: APP_HTTP_ADDR
              value: ":8080"
            - name: BOTUSER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-client-configuration
                  key: botusertoken
            - name: VERIFICATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-client-configuration
                  key: verificationtoken
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: http
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /health
              port: http
              scheme: HTTP
---
apiVersion: v1
kind: Service
metadata:
  name: prod-slack-client
  labels:
    app: slack-client
    env: prod
spec:
  type: ClusterIP
  selector:
    app: slack-client
    env: prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      name: http
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: prod-slack-client
  labels:
    app: slack-client
    env: prod
spec:
  host: slack-bot.kscout.io
  path: /
  to:
    kind: Service
    name: prod-slack-client
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
status:
  ingress:
    - host: slack-bot.kscout.io

