apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: prod-slack-api
  labels:
    app: slack-api
    env: prod
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          containers:
            - name: slack-api
              image: kscout/slack-chat-bot-api:prod-latest
              env:
                - name: APP_HTTP_ADDR
                  value: ":8080"
                - name: BOTUSER_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: slack-api-configuration
                      key: botusertoken
                - name: VERIFICATION_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: slack-api-configuration
                      key: verificationtoken

#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: prod-slack-api
#  labels:
#    app: slack-api
#    env: prod
#spec:
#  type: ClusterIP
#  selector:
#    app: slack-api
#    env: prod
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: http
#      name: http
#---
#apiVersion: route.openshift.io/v1
#kind: Route
#metadata:
#  name: prod-bot-api
#  labels:
#    app: bot-api
#    env: prod
#spec:
#  host: bot.kscout.io
#  path: /
#  to:
#    kind: Service
#    name: prod-bot-api
#    weight: 100
#  port:
#    targetPort: http
#  tls:
#    termination: edge
#status:
#  ingress:
#    - host: bot.kscout.io
