# Global shared chart configuration
global:
  # Deployment environment, usually "prod" or "staging"
  env:

  # App being deployed
  app: slack-client

# HTTP service chart
http:
  # Serve under host
  defaultHost: slack-bot.kscout.io

  # Internal app container port
  port: 8080

  # Configuration
  configMap:
    - key: externalURL
      value: "{{ .Values.defaultHost }}"
      envKey: APP_EXTERNAL_URL
    - key: httpAddr
      value: ":{{ .Values.port }}"
      envKey: APP_HTTP_ADDR

  # Mount secret under path
  secretMount: /mnt/secret

  # Pass Mongo credentials to app container
  mongoEnabled: true
